#!/bin/bash
# build-indexes.sh — regenerate one index.md per entity folder.
#
# Progressive disclosure: an agent should be able to answer "open decisions owned by X" by reading
# one small file, not by opening fifty. A mature hub is dozens of entity notes; without an index an
# agent must enumerate them blind, paying the cost of the entity layer without its main benefit.
#
# NEVER hand-edit an index.md. This script overwrites them. Run it on apply/commit.
# Retired and superseded notes are excluded — they are kept on disk for the audit trail,
# but they are not live claims and must not compete for attention.
#
# The emitted frontmatter carries `lifecycle: active` (v1.15). An index is a hub-produced
# document, so [ CURRENCY ] in hub-scan.sh requires the field, and a file whose header forbids
# hand edits can only satisfy that through its generator. The value is true by construction:
# the index lists active notes only and is regenerated in place, never superseded.
#
# Notes marked restricted, a line beginning `sensitivity: restricted` anywhere in the note, are
# also excluded (v1.16). A generated index is a summary surface, and restricted content is never
# surfaced in summaries; the [ RESTRICTED ] check in hub-scan.sh fails the scan if a restricted
# note's name reaches an index, and this exclusion is what makes that hit clearable by
# regeneration. The note stays on disk and in git, inside its own bound.

HUB="$(cd "$(dirname "$0")" && pwd)"
ENTITY_DIRS="decisions risks stakeholders milestones partners relationships corrections"

fm() {
  awk -v k="$2" '
    /^---$/ { n++; if (n==2) exit; next }
    n==1 {
      if ($0 ~ "^" k ":") {
        sub("^" k ":[ ]*", ""); sub(/[ \t]+#.*$/, "")
        gsub(/^[ \t]+|[ \t]+$/, ""); gsub(/^"|"$/, ""); print; exit
      }
    }' "$1"
}

# Refuse to build from a read that cannot be trusted.
#
# This script derives content from files it reads and then overwrites a file with the result. In
# cloud-synced storage an on-demand placeholder returns empty on first read while its directory
# entry still reports the real size, so `fm` would come back blank for every field: a note would
# be listed with an empty title and empty columns, and a retired note whose `lifecycle` read as
# nothing would be republished as live. That is a wrong index written with full confidence.
# Stale indexes are harmless; wrong ones are not. So probe first and build nothing if any note
# is unreadable. See STANDARD.md Rule 3, "A read of synced storage can report absence that is
# only lag".
file_size() { stat -f%z "$1" 2>/dev/null || stat -c%s "$1" 2>/dev/null; }
unreadable=""
for dir in $ENTITY_DIRS; do
  [ -d "$HUB/$dir" ] || continue
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    sz=$(file_size "$f"); sz=${sz:-0}
    got=$(head -c 1 "$f" 2>/dev/null | wc -c | tr -d ' '); got=${got:-0}
    if [ "$sz" -gt 0 ] && [ "$got" -eq 0 ]; then
      unreadable="${unreadable}  - ${f#$HUB/} (${sz} bytes on disk, read returned nothing)"$'\n'
    fi
  done <<< "$(find "$HUB/$dir" -maxdepth 1 -name '*.md' ! -name 'TEMPLATE.md' ! -name 'index.md' ! -name 'README.md' 2>/dev/null | sort)"
done
if [ -n "$unreadable" ]; then
  echo "ABORTED: note(s) could not be read, so no index was rewritten:" >&2
  printf '%s' "$unreadable" >&2
  echo "These are readable-later, not empty. Re-run once the sync has materialised them." >&2
  exit 1
fi

total=0
for dir in $ENTITY_DIRS; do
  [ -d "$HUB/$dir" ] || continue
  notes=$(find "$HUB/$dir" -maxdepth 1 -name '*.md' ! -name 'TEMPLATE.md' ! -name 'index.md' ! -name 'README.md' 2>/dev/null | sort)

  out="$HUB/$dir/index.md"
  {
    echo "---"
    echo "type: index"
    echo "title: ${dir} — index"
    echo "description: Auto-generated index of ${dir}. Do not hand-edit; run build-indexes.sh."
    echo "tags: [index, ${dir}]"
    echo "resource: ./"
    echo "lifecycle: active"
    echo "timestamp: $(date '+%Y-%m-%d')"
    echo "---"
    echo
    echo "# ${dir} — index"
    echo
    echo "_Auto-generated by \`build-indexes.sh\`. Do not edit by hand — your changes will be overwritten._"
    echo "_Active notes only. Retired, superseded and restricted-marked notes remain on disk and in git, but are not listed here._"
    echo

    if [ -z "$notes" ]; then
      echo "_None yet._"
    else
      case "$dir" in
        decisions)   echo "| Decision | Status | Decided by | Date |"; echo "|---|---|---|---|" ;;
        risks)       echo "| Risk | Status | Impact | Owner |"; echo "|---|---|---|---|" ;;
        stakeholders) echo "| Person | Role | Involvement |"; echo "|---|---|---|" ;;
        milestones)  echo "| Milestone | Target | Owner |"; echo "|---|---|---|" ;;
        partners)    echo "| Partner | Status |"; echo "|---|---|" ;;
        corrections) echo "| Correction | Rule | Trigger | Date |"; echo "|---|---|---|---|" ;;
        relationships) echo "| Assertion | Predicate | Confidence |"; echo "|---|---|---|" ;;
      esac
      while IFS= read -r f; do
        [ -z "$f" ] && continue
        lc=$(fm "$f" "lifecycle")
        case "$lc" in retired|superseded) continue ;; esac
        # Restricted notes never reach a summary surface; see the header comment (v1.16).
        grep -Eq '^sensitivity:[[:space:]]*restricted([^A-Za-z0-9-]|$)' "$f" 2>/dev/null && continue
        base=$(basename "$f" .md)
        title=$(fm "$f" "title"); [ -z "$title" ] && title="$base"
        link="[${title}](${base}.md)"
        case "$dir" in
          decisions)    echo "| $link | $(fm "$f" status) | $(fm "$f" decidedBy) | $(fm "$f" date) |" ;;
          risks)        echo "| $link | $(fm "$f" status) | $(fm "$f" impact) | $(fm "$f" owner) |" ;;
          stakeholders) echo "| $link | $(fm "$f" role) | $(fm "$f" involvement) |" ;;
          milestones)   echo "| $link | $(fm "$f" targetDate) | $(fm "$f" owner) |" ;;
          partners)     echo "| $link | $(fm "$f" status) |" ;;
          corrections)  echo "| $link | $(fm "$f" rule) | $(fm "$f" trigger) | $(fm "$f" date) |" ;;
          relationships) echo "| $link | $(fm "$f" predicate) | $(fm "$f" confidence) |" ;;
        esac
        total=$((total + 1))
      done <<< "$notes"
    fi
  } > "$out"
  echo "  wrote $dir/index.md"
done
echo "indexes rebuilt (${total} active note(s) listed)"
